/*
Zinc Search engine API

Zinc Search engine API documents https://docs.zincsearch.com

API version: 0.2.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// MetaTermQuery struct for MetaTermQuery
type MetaTermsQuery struct {
	Boost *float32 `json:"boost,omitempty"`
	Value *map[string]interface{} `json:"value,omitempty"`
}

// NewMetaTermQuery instantiates a new MetaTermQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaTermsQuery() *MetaTermsQuery {
	this := MetaTermsQuery{}
	return &this
}

// NewMetaTermQueryWithDefaults instantiates a new MetaTermQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaTermsQueryWithDefaults() *MetaTermsQuery {
	this := MetaTermsQuery{}
	return &this
}

// GetBoost returns the Boost field value if set, zero value otherwise.
func (o *MetaTermsQuery) GetBoost() float32 {
	if o == nil || o.Boost == nil {
		var ret float32
		return ret
	}
	return *o.Boost
}

// GetBoostOk returns a tuple with the Boost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaTermsQuery) GetBoostOk() (*float32, bool) {
	if o == nil || o.Boost == nil {
		return nil, false
	}
	return o.Boost, true
}

// HasBoost returns a boolean if a field has been set.
func (o *MetaTermsQuery) HasBoost() bool {
	if o != nil && o.Boost != nil {
		return true
	}

	return false
}

// SetBoost gets a reference to the given float32 and assigns it to the Boost field.
func (o *MetaTermsQuery) SetBoost(v float32) {
	o.Boost = &v
}


// GetValue returns the Value field value if set, zero value otherwise.
func (o *MetaTermsQuery) GetValue() map[string]interface{} {
	if o == nil || o.Value == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaTermsQuery) GetValueOk() (*map[string]interface{}, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *MetaTermsQuery) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *MetaTermsQuery) SetValue(v map[string]interface{}) {
	o.Value = &v
}

func (o MetaTermsQuery) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Boost != nil {
		toSerialize["boost"] = o.Boost
	}
	for k, v := range *o.Value {
		toSerialize[k] = v
	}
	return json.Marshal(toSerialize)
}

type NullableMetaTermsQuery struct {
	value *MetaTermQuery
	isSet bool
}

func (v NullableMetaTermsQuery) Get() *MetaTermQuery {
	return v.value
}

func (v *NullableMetaTermsQuery) Set(val *MetaTermQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaTermsQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaTermsQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaTermsQuery(val *MetaTermQuery) *NullableMetaTermsQuery {
	return &NullableMetaTermsQuery{value: val, isSet: true}
}

func (v NullableMetaTermsQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaTermsQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


